In [1]:
import pymongo
import pandas as pd
import numpy as np

In [2]:
client = pymongo.MongoClient("localhost",connect=False)
db = client["Zufang-beijing-530"]
table = db["zufang"]
data = pd.DataFrame(list(table.find()))
del data["_id"]
del data["更新时间"]
df = data.drop_duplicates()
df.tail(3)

,交租方式,地址,建筑面积,户型,标签,标题,楼层,租金,网址,装修
120616,押一付三,朝阳 - 晶都国际,98,2室2厅,None,晶都国际 西南 2室 不临街,17/22,9500,http://m.fang.com/zf/bj/JHAGT_391026842_fa022d...,精装修
120619,押一付三,朝阳 - 东方雅苑,100,2室2厅,"交通便利,周边配套齐,独门独卫",西大望路 东方雅苑二居!多话没有!看图可短租可月付,6/12,7500,http://m.fang.com/zf/bj/JHAGT_388612520_569e8c...,豪华装修
120620,押一付三,朝阳 - 苹果社区,55,1室1厅,None,苹果艺术街区二装经典南向开间 家装齐全 整洁干净 温馨入住,10/25,6800,http://m.fang.com/zf/bj/JHAGT_390944379_a6049f...,精装修

In [3]:
def trans_int(x):
    try:
        return int(x)
    except:
        return np.nan
df = df.iloc[:,[1,2,3,6,7,8]].dropna()
df["建筑面积"] =df["建筑面积"].apply(trans_int)
df.head()

,地址,建筑面积,户型,楼层,租金,网址
0,丰台 - 恒富中街,80.0,2室1厅,12/14,6000,http://m.fang.com/zf/bj/JHAGT_390439878_f1f665...
1,丰台 - 看丹苑,80.0,2室2厅,3/6,4800,http://m.fang.com/zf/bj/JHAGT_390440156_e7e491...
2,房山 - 金鑫苑,130.0,3室2厅,1/6,1900,http://m.fang.com/zf/bj/JHAGT_388017056_ae8fda...
3,朝阳 - 富力又一城,90.0,2室1厅,5/21,5400,http://m.fang.com/zf/bj/JHAGT_389127017_11aa12...
4,朝阳 - 天居园,133.0,2室1厅,31/32,9200,http://m.fang.com/zf/bj/JHAGT_389656618_d5f215...

In [4]:
df = df.rename(columns={"地址":"name","建筑面积":"area","户型":"house_type","租金":"price","网址":"url","楼层":"floor"})
df.tail(3)

,name,area,house_type,floor,price,url
120616,朝阳 - 晶都国际,98.0,2室2厅,17/22,9500,http://m.fang.com/zf/bj/JHAGT_391026842_fa022d...
120619,朝阳 - 东方雅苑,100.0,2室2厅,6/12,7500,http://m.fang.com/zf/bj/JHAGT_388612520_569e8c...
120620,朝阳 - 苹果社区,55.0,1室1厅,10/25,6800,http://m.fang.com/zf/bj/JHAGT_390944379_a6049f...

In [5]:
df["average_price"] = (df["price"]/df["area"]).apply(trans_int)
df.tail(3)

,name,area,house_type,floor,price,url,average_price
120616,朝阳 - 晶都国际,98.0,2室2厅,17/22,9500,http://m.fang.com/zf/bj/JHAGT_391026842_fa022d...,96.0
120619,朝阳 - 东方雅苑,100.0,2室2厅,6/12,7500,http://m.fang.com/zf/bj/JHAGT_388612520_569e8c...,75.0
120620,朝阳 - 苹果社区,55.0,1室1厅,10/25,6800,http://m.fang.com/zf/bj/JHAGT_390944379_a6049f...,123.0

In [6]:
df = df[df.average_price>50]
df = df[df.average_price<70]
df.sort_values("area")

,name,area,house_type,floor,price,url,average_price
105553,通州 - 果园225号院,8.0,3室1厅,3/6,500,http://m.fang.com/zf/bj/JHAGT_389984063_c6d9a7...,62.0
30626,海淀 - 颐阳山水居西区,10.0,3室1厅,2/6,650,http://m.fang.com/zf/bj/JHAGT_390865863_1c0edd...,65.0
80358,海淀 - 京泉馨苑,10.0,3室1厅,3/6,650,http://m.fang.com/zf/bj/JHAGT_390965170_bb24b7...,65.0
120439,海淀 - 上奥世纪中心,12.0,3室1厅,1/6,800,http://m.fang.com/zf/bj/JHAGT_390840512_8a7cd1...,66.0
4689,通州 - 加华印象街,12.0,3室1厅,5/11,650,http://m.fang.com/zf/bj/JHAGT_390153707_372cbd...,54.0
15953,通州 - 翠屏南里,12.0,3室1厅,1/6,800,http://m.fang.com/zf/bj/JHAGT_389984109_44c74b...,66.0
2724,昌平 - 龙兴园北区,12.0,2室1厅,3/6,800,http://m.fang.com/zf/bj/JHAGT_390436203_d8ed7a...,66.0
88932,海淀 - 常青园北里,13.0,3室1厅,11/23,900,http://m.fang.com/zf/bj/JHAGT_390964810_a2767e...,69.0
27918,丰台 - 方庄南路18号院,13.0,3室1厅,7/22,800,http://m.fang.com/zf/bj/JHAGT_390788637_2660e8...,61.0
85715,丰台 - 正邦嘉园一期,14.0,3室2厅,13/26,900,http://m.fang.com/zf/bj/JHAGT_390969048_7efdb9...,64.0
81210,海淀 - 溪山嘉园,14.0,3室1厅,3/6,950,http://m.fang.com/zf/bj/JHAGT_390965738_9ddf39...,67.0
19412,海淀 - 溪山嘉园,14.0,3室1厅,3/6,950,http://m.fang.com/zf/bj/JHAGT_390733418_9ddf39...,67.0
15954,通州 - 鑫苑小区,15.0,1室1厅,5/6,800,http://m.fang.com/zf/bj/JHAGT_389984401_4ad905...,53.0
2722,昌平 - 新龙城,15.0,4室1厅,3/6,1000,http://m.fang.com/zf/bj/JHAGT_390402110_ce756c...,66.0
90001,海淀 - 天香颐北里,15.0,3室1厅,3/6,1000,http://m.fang.com/zf/bj/JHAGT_390965676_44a4f5...,66.0
20688,昌平 - 领秀慧谷,15.0,3室1厅,2/6,1000,http://m.fang.com/zf/bj/JHAGT_384626626_8b67ca...,66.0
20689,昌平 - 佰嘉城,15.0,3室1厅,2/6,1000,http://m.fang.com/zf/bj/JHAGT_384627141_1e1e61...,66.0
79790,朝阳 - 百子湾家园,15.0,2室1厅,11/16,900,http://m.fang.com/zf/bj/JHAGT_379129601_211c71...,60.0
2719,昌平 - 朱辛庄新村南区,15.0,3室1厅,6/10,800,http://m.fang.com/zf/bj/JHAGT_390401650_67f18f...,53.0
2926,昌平 - 龙兴园北区,15.0,2室1厅,3/6,850,http://m.fang.com/zf/bj/JHAGT_390731784_ebfd94...,56.0
2757,昌平 - 二拨子新村,15.0,3室1厅,3/6,1000,http://m.fang.com/zf/bj/JHAGT_390732730_00f9b2...,66.0
2907,昌平 - 融泽嘉园,15.0,3室1厅,15/29,1000,http://m.fang.com/zf/bj/JHAGT_390732660_f677e5...,66.0
4690,通州 - 武夷花园水仙园,15.0,3室1厅,2/6,850,http://m.fang.com/zf/bj/JHAGT_390153738_482109...,56.0
61552,昌平 - 朱辛庄新村北区,15.0,3室1厅,3/15,1000,http://m.fang.com/zf/bj/JHAGT_390878640_d922f4...,66.0
2715,昌平 - 龙兴园北区,15.0,2室1厅,3/6,850,http://m.fang.com/zf/bj/JHAGT_390400160_ebfd94...,56.0
2711,昌平 - 朱辛庄新村,15.0,3室1厅,3/6,900,http://m.fang.com/zf/bj/JHAGT_390732745_e20a7d...,60.0
105554,通州 - 李老新村,15.0,4室1厅,4/6,900,http://m.fang.com/zf/bj/JHAGT_389984579_85c11b...,60.0
2241,丰台 - 顶秀欣园东苑,15.0,3室1厅,10/28,1000,http://m.fang.com/zf/bj/JHAGT_387484799_12d6e9...,66.0
2527,昌平 - 天通苑西三区,15.0,3室1厅,2/6,900,http://m.fang.com/zf/bj/JHAGT_390615911_817ff8...,60.0
15956,通州 - 葵花社,16.0,3室1厅,12/12,850,http://m.fang.com/zf/bj/JHAGT_389984502_27b9e3...,53.0
...,...,...,...,...,...,...,...
32778,朝阳 - 中海紫荆豪庭,285.0,4室2厅,28/30,18000,http://m.fang.com/zf/bj/JHAGT_389791658_daf9f9...,63.0
36708,朝阳 - 中海紫荆豪庭,285.0,4室2厅,28/30,18000,http://m.fang.com/zf/bj/JHAGT_389799762_daf9f9...,63.0
40660,朝阳 - 中海紫荆豪庭,285.0,3室2厅,28/30,19000,http://m.fang.com/zf/bj/JHAGT_390342815_eb2f55...,66.0
60064,海淀 - 西山华府禧园,286.0,4室2厅,7/7,20000,http://m.fang.com/zf/bj/JHAGT_387090240_3f6311...,69.0
8594,朝阳 - 后现代城,286.0,8室4厅,10/14,16800,http://m.fang.com/zf/bj/JHAGT_390745490_da8757...,58.0
16923,海淀 - 亿城西山华府,286.0,4室2厅,3/7,20000,http://m.fang.com/zf/bj/JHAGT_386937650_3f6311...,69.0
60098,海淀 - 雅世合金公寓,288.0,4室2厅,1/10,20000,http://m.fang.com/zf/bj/JHAGT_388092106_29d27d...,69.0
49022,海淀 - 雅世合金公寓,288.0,4室2厅,1/9,20000,http://m.fang.com/zf/bj/JHAGT_390927826_ce273b...,69.0
50455,海淀 - 雅世合金公寓,288.0,4室2厅,1/10,20000,http://m.fang.com/zf/bj/JHAGT_390319397_29d27d...,69.0
7124,大兴 - 卡尔公寓,290.0,5室2厅,1/3,17000,http://m.fang.com/zf/bj/JHAGT_389008862_df9a39...,58.0
76481,海淀 - 保利西山林语,292.0,3室1厅,1/6,15000,http://m.fang.com/zf/bj/JHAGT_387580352_8c8900...,51.0
29754,海淀 - 亿城西山公馆,293.0,5室3厅,1/6,17500,http://m.fang.com/zf/bj/JHAGT_388861836_8631b1...,59.0
56374,顺义 - 名都园,294.0,4室3厅,1/4,18000,http://m.fang.com/zf/bj/JHAGT_389904830_7e7dcb...,61.0
24717,大兴 - 卡尔公寓,300.0,6室3厅,3/3,18000,http://m.fang.com/zf/bj/JHAGT_390602660_170ab9...,60.0
10076,海淀 - 北辰香麓,303.0,4室2厅,3/3,16000,http://m.fang.com/zf/bj/JHAGT_389070132_362bfd...,52.0
53222,顺义 - 阿凯笛亚庄园公寓,340.0,4室2厅,1/3,21000,http://m.fang.com/zf/bj/JHAGT_390421156_74ba00...,61.0
45312,海淀 - 西山美墅馆公寓,360.0,4室2厅,1/4,23000,http://m.fang.com/zf/bj/JHAGT_385536430_594937...,63.0
71091,顺义 - 阿凯笛亚庄园公寓,360.0,4室2厅,1/3,23000,http://m.fang.com/zf/bj/JHAGT_389518104_00f3cc...,63.0
5742,海淀 - 鲁艺上河村,364.0,5室2厅,13/15,22000,http://m.fang.com/zf/bj/JHAGT_390757547_241e1e...,60.0
34602,顺义 - 阿凯笛亚庄园公寓,380.0,5室3厅,1/4,23000,http://m.fang.com/zf/bj/JHAGT_390421316_b26a07...,60.0
115652,东城 - 北京上舍,385.0,4室2厅,1/4,20000,http://m.fang.com/zf/bj/JHAGT_391018437_5ab277...,51.0
88828,东城 - 北京上舍,385.0,4室2厅,1/4,20000,http://m.fang.com/zf/bj/JHAGT_390452234_5ab277...,51.0
13260,顺义 - 万通天竺新新家园溪悦府,400.0,5室3厅,1/4,27600,http://m.fang.com/zf/bj/JHAGT_390451795_943832...,69.0
39108,朝阳 - 滨水动漫城,400.0,4室3厅,20/21,23000,http://m.fang.com/zf/bj/JHAGT_390381458_dc7bb2...,57.0
37803,丰台 - 璞瑅,400.0,4室3厅,16/29,23000,http://m.fang.com/zf/bj/JHAGT_388705667_f4f521...,57.0
12793,大兴 - 富力盛悦居,400.0,5室1厅,13/21,22500,http://m.fang.com/zf/bj/JHAGT_389020789_881e7f...,56.0
20199,海淀 - 五矿万科如园,448.0,4室3厅,1/11,28000,http://m.fang.com/zf/bj/JHAGT_390054721_8f260e...,62.0
16307,海淀 - 五矿万科如园,448.0,4室3厅,1/11,28000,http://m.fang.com/zf/bj/JHAGT_390024548_8f260e...,62.0
17892,顺义 - 中粮祥云国际生活区住宅,580.0,5室3厅,1/3,40000,http://m.fang.com/zf/bj/JHAGT_390540907_ff29bf...,68.0
26963,通州 - 天赐良园,670.0,99室99厅,1/3,40000,http://m.fang.com/zf/bj/JHAGT_390616636_3b26db...,59.0

In [7]:
df = df[df.area<80].reset_index()
df.tail(3)

,index,name,area,house_type,floor,price,url,average_price
1879,120439,海淀 - 上奥世纪中心,12.0,3室1厅,1/6,800,http://m.fang.com/zf/bj/JHAGT_390840512_8a7cd1...,66.0
1880,120507,丰台 - 永外果园,70.0,2室1厅,4/12,4800,http://m.fang.com/zf/bj/JHAGT_391026754_00d6a0...,68.0
1881,120560,丰台 - 南庭新苑,55.0,1室1厅,9/16,3600,http://m.fang.com/zf/bj/JHAGT_390266504_46c5c9...,65.0

In [8]:
del df["index"]

In [9]:
df.to_csv("zufang_me.csv",encoding="utf-8")

In [10]:
df2 = pd.read_csv("zufang2.csv")
del df2["Unnamed: 0"]
df2.head()

          lon        lat          name  number location
0  116.410285  39.925557    东城 - 东单四合院       3       东城
1  116.437104  39.890148  东城 - FREE自由季      25       东城
2  116.436151  39.935898     东城 - 东环公寓       2       东城
3  116.416490  39.960881     东城 - 化工大院      14       东城
4  116.412749  39.942675   东城 - 交道口北二条       6       东城

In [11]:
df = df.set_index("name")
df2 = df2.set_index("name")

In [12]:
df3 = pd.merge(df,df2,left_index = True,right_index=True)
df3.head()

,area,house_type,floor,price,url,average_price,lon,lat,number,location
name,,,,,,,,,,
东城 - 兴隆都市馨园,74.0,1室1厅,1/6,4400,http://m.fang.com/zf/bj/JHAGT_390534166_22ff0f...,59.0,116.414045,39.895318,83,东城
东城 - 兴隆都市馨园,74.0,1室1厅,1/6,4400,http://m.fang.com/zf/bj/JHAGT_390279530_22ff0f...,59.0,116.414045,39.895318,83,东城
东城 - 安外大街3号院,50.0,2室1厅,2/12,3200,http://m.fang.com/zf/bj/JHAGT_390936003_3eea2f...,64.0,116.406694,39.961701,6,东城
东城 - 安外大街3号院,50.0,2室1厅,2/12,3200,http://m.fang.com/zf/bj/JHAGT_390593445_3eea2f...,64.0,116.406694,39.961701,6,东城
东城 - 幸福家园,57.0,1室1厅,18/20,3600,http://m.fang.com/zf/bj/JHAGT_390087307_88e87f...,63.0,116.430484,39.892307,93,东城

In [13]:
del df3["number"]

In [14]:
df3=df3.drop_duplicates()

df3.head()

In [15]:
df3.head()

,area,house_type,floor,price,url,average_price,lon,lat,location
name,,,,,,,,,
东城 - 兴隆都市馨园,74.0,1室1厅,1/6,4400,http://m.fang.com/zf/bj/JHAGT_390534166_22ff0f...,59.0,116.414045,39.895318,东城
东城 - 兴隆都市馨园,74.0,1室1厅,1/6,4400,http://m.fang.com/zf/bj/JHAGT_390279530_22ff0f...,59.0,116.414045,39.895318,东城
东城 - 安外大街3号院,50.0,2室1厅,2/12,3200,http://m.fang.com/zf/bj/JHAGT_390936003_3eea2f...,64.0,116.406694,39.961701,东城
东城 - 安外大街3号院,50.0,2室1厅,2/12,3200,http://m.fang.com/zf/bj/JHAGT_390593445_3eea2f...,64.0,116.406694,39.961701,东城
东城 - 幸福家园,57.0,1室1厅,18/20,3600,http://m.fang.com/zf/bj/JHAGT_390087307_88e87f...,63.0,116.430484,39.892307,东城

In [16]:
df3.to_csv("zufang_fitme.csv",encoding="utf-8")

In [17]:
df3.head()

,area,house_type,floor,price,url,average_price,lon,lat,location
name,,,,,,,,,
东城 - 兴隆都市馨园,74.0,1室1厅,1/6,4400,http://m.fang.com/zf/bj/JHAGT_390534166_22ff0f...,59.0,116.414045,39.895318,东城
东城 - 兴隆都市馨园,74.0,1室1厅,1/6,4400,http://m.fang.com/zf/bj/JHAGT_390279530_22ff0f...,59.0,116.414045,39.895318,东城
东城 - 安外大街3号院,50.0,2室1厅,2/12,3200,http://m.fang.com/zf/bj/JHAGT_390936003_3eea2f...,64.0,116.406694,39.961701,东城
东城 - 安外大街3号院,50.0,2室1厅,2/12,3200,http://m.fang.com/zf/bj/JHAGT_390593445_3eea2f...,64.0,116.406694,39.961701,东城
东城 - 幸福家园,57.0,1室1厅,18/20,3600,http://m.fang.com/zf/bj/JHAGT_390087307_88e87f...,63.0,116.430484,39.892307,东城

In [18]:
df3 = df3.reset_index()

In [19]:
del df3["url"]

In [20]:
df3 = df3.drop_duplicates()

In [21]:
df3.tail(3)

,name,area,house_type,floor,price,average_price,lon,lat,location
1866,顺义 - 马可汇,61.0,1室1厅,5/12,3500,57.0,116.619295,40.132138,顺义
1867,顺义 - 马可汇,69.0,1室1厅,2/12,3600,52.0,116.619295,40.132138,顺义
1869,顺义 - 龙湖香醍漫步公寓,38.0,1室,2/8,2200,57.0,116.665665,40.206579,顺义

In [23]:
df4 = df3.groupby("name").count().iloc[:,[0]].rename(columns={"area":"count"})
df4.head()

              count
name
东城 - 兴隆都市馨园       1
东城 - 安外大街3号院      1
东城 - 幸福家园         1
东城 - 忠实里小区        1
东城 - 新奥洋房         1

In [24]:
df5 = df3.groupby("name").mean()
df5.head()

              area   price  average_price         lon        lat
name
东城 - 兴隆都市馨园   74.0  4400.0           59.0  116.414045  39.895318
东城 - 安外大街3号院  50.0  3200.0           64.0  116.406694  39.961701
东城 - 幸福家园     57.0  3600.0           63.0  116.430484  39.892307
东城 - 忠实里小区    68.0  4700.0           69.0  116.445803  39.897931
东城 - 新奥洋房     56.0  3400.0           60.0  116.409396  39.864101

In [32]:
df6 = pd.merge(df4,df5,left_index=True,right_index=True)
df6 = pd.merge(df6,df2.iloc[:,[3]],left_index=True,right_index=True)
df6 = df6.rename(columns={"average_price":"mean_prc","count":"number"})
df6.head()

              number  area   price  mean_prc         lon        lat location
name
东城 - 兴隆都市馨园        1  74.0  4400.0      59.0  116.414045  39.895318       东城
东城 - 安外大街3号院       1  50.0  3200.0      64.0  116.406694  39.961701       东城
东城 - 幸福家园          1  57.0  3600.0      63.0  116.430484  39.892307       东城
东城 - 忠实里小区         1  68.0  4700.0      69.0  116.445803  39.897931       东城
东城 - 新奥洋房          1  56.0  3400.0      60.0  116.409396  39.864101       东城

In [33]:
df6.to_csv("zufang4.csv",encoding="utf-8")